#!/bin/sh

# lint — Linter for Reference Utility

# Reference Utility (https://github.com/melusina-org/reference-utility)
# This file is part of Reference Utility.
#
# Copyright © 2023 Michaël Le Barbier
# All rights reserved.

# This file must be used under the terms of the MIT License.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution. The terms
# are also available at https://opensource.org/licenses/MIT

: ${TOPLEVELDIR:=$(git rev-parse --show-toplevel)}

lint_sbcl()
{
    sbcl --noinform --disable-debugger "$@"
}

lint_main()
{
    lint_sbcl --load "${TOPLEVELDIR}/libexec/lisp/setup.lisp"\
	      --eval '(org.melusina.atelier:lint
 #p"src"
 #p"testsuite"
 #p"libexec/lisp/setup.lisp"
 #p"development"
 #p"operation")'
}

lint_main "$@"

# End of file `lint'
